"use client";
import { FormEvent, useEffect, useState } from "react";
type Score = { participant_name: string; score: number; played_at: string };
export function Arcade() {
  const [name, setName] = useState(""); const [score, setScore] = useState(0); const [running, setRunning] = useState(false); const [seconds, setSeconds] = useState(20); const [scores, setScores] = useState<Score[]>([]); const [message, setMessage] = useState("");
  const loadLeaderboard = async () => { const response = await fetch("/api/leaderboard", { cache: "no-store" }); const data = await response.json(); setScores(data.scores); };
  useEffect(() => { loadLeaderboard(); }, []);
  useEffect(() => { if (!running) return; if (seconds === 0) { setRunning(false); setMessage("Partie terminée — enregistrez votre score !"); return; } const timer = window.setTimeout(() => setSeconds((value) => value - 1), 1000); return () => window.clearTimeout(timer); }, [running, seconds]);
  const start = () => { if (!name.trim()) { setMessage("Entrez votre prénom ou pseudo avant de jouer."); return; } setScore(0); setSeconds(20); setMessage("Attrapez les pixels !"); setRunning(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (running || !name.trim()) return; const response = await fetch("/api/scores", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, score }) }); if (!response.ok) { setMessage("Impossible d’enregistrer le score."); return; } setMessage("Score enregistré dans le classement !"); loadLeaderboard(); };
  return <main className="arcade-bg min-h-screen px-5 py-10 sm:px-10"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-col justify-between gap-4 border-b-4 border-[#14213d] pb-5 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-bold tracking-[.22em] text-[#ff6b35]">SERVICE COM · INTRANET</p><h1 className="text-4xl font-black tracking-tight sm:text-6xl">COM ARCADE</h1></div><p className="max-w-xs text-sm font-bold">Le mini-jeu de la semaine. Jouez, marquez des points, montez au classement.</p></header><section className="grid gap-7 lg:grid-cols-[1.25fr_.75fr]"><div className="border-4 border-[#14213d] bg-[#14213d] p-3 shadow-[8px_8px_0_#ff6b35]"><div className="relative flex min-h-[360px] flex-col items-center justify-center overflow-hidden bg-[#20134b] p-6 text-center text-white"><p className="absolute left-5 top-5 font-mono text-sm text-[#9ee7ff]">NEON DODGER / SEMAINE 01</p><p className="mb-2 text-7xl font-black text-[#ffd166]">{score}</p><p className="mb-7 text-sm font-bold tracking-[.2em]">POINTS</p><button type="button" aria-label="Attraper un pixel" onClick={() => running && setScore((value) => value + 10)} className={`h-24 w-24 border-4 border-white bg-[#ff6b35] text-4xl shadow-[5px_5px_0_#ffd166] transition hover:scale-110 active:scale-90 ${running ? "animate-pulse cursor-crosshair" : "opacity-40"}`}>✦</button><p className="mt-7 font-mono text-xl">{seconds.toString().padStart(2, "0")} SECONDES</p></div><div className="flex gap-3 bg-[#14213d] pt-3"><button onClick={start} type="button" className="flex-1 bg-[#ffd166] px-4 py-3 font-black text-[#14213d] hover:bg-white">{running ? "EN COURS…" : "NOUVELLE PARTIE"}</button></div></div><aside className="border-4 border-[#14213d] bg-white p-5 shadow-[8px_8px_0_#14213d]"><h2 className="mb-4 text-2xl font-black">TABLEAU DES SCORES</h2><ol className="space-y-2">{scores.length ? scores.map((item, index) => <li key={`${item.participant_name}-${index}`} className="flex justify-between border-b-2 border-[#f1e5c7] pb-2 font-bold"><span><b className="mr-3 text-[#ff6b35]">{index + 1}</b>{item.participant_name}</span><span>{item.score}</span></li>) : <li className="text-sm">Aucun score pour l’instant. À vous de jouer.</li>}</ol><form onSubmit={save} className="mt-7 border-t-2 border-[#14213d] pt-5"><label className="mb-2 block text-sm font-bold" htmlFor="name">VOTRE PRÉNOM / PSEUDO</label><input id="name" maxLength={40} value={name} onChange={(event) => setName(event.target.value)} className="w-full border-2 border-[#14213d] px-3 py-2" placeholder="Camille" /><button disabled={running} className="mt-3 w-full bg-[#ff6b35] px-4 py-3 font-black text-white disabled:opacity-40">ENREGISTRER {score} PTS</button></form>{message && <p className="mt-4 text-sm font-bold text-[#ff6b35]">{message}</p>}</aside></section></div></main>;
}
